name: Prepare dist and package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  prepare-dist:
    name: Prepare dist and upload package.zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npx prettier --check "src/**/*.{js,css,html}"

      - name: Run ESLint
        run: npx eslint "src/**/*.js"

      - name: Run tests (if defined)
        run: |
          # If package.json has a `test` script, run it; otherwise skip
          if node -e "const p=require('./package.json'); console.log(Boolean(p.scripts && p.scripts.test));" | grep -q true; then
            echo "Running npm test..."
            npm test
          else
            echo "No test script defined; skipping npm test"
          fi

      - name: Run prepare:dist
        run: npm run prepare:dist

      - name: Create zip
        run: npm run zip

      - name: Upload package.zip
        uses: actions/upload-artifact@v4
        with:
          name: package-zip
          path: package.zip
